name: Generate Greeting Card with Docker

on:
 push:
   branches: [main]

jobs:
  generate_and_commit:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@4
         
       - name: Set up Docker buildx
         id: buildx
         uses: docker/setup-buildx-action@v3

       - name: Build Docker image
         uses: docker/build-push-action@v5
         with:
          context: .
          dockerfile: Dockerfile
          tags: my-greeting-app:latest # You can choose a different tag

       - name: Run Docker container and generate greeting
         run: |
          docker run --rm my-greeting-app:latest --recipient "Docker User" --message "Greetings from inside a container

       - name: Commit and push changes
         uses: stefanzweifel/git-auto-commit-action@v5
         with:
          commit_message: "Automated: Generated a new greeting card via Docker"
